INSERT INTO PET (NAME, AGE, PET_TYPE, FUR_COLOUR, LOCATION) VALUES ('Barnaby', 2, 'BIRD', 'Yellow', 'North Shelter');
INSERT INTO PET (NAME, AGE, PET_TYPE, FUR_COLOUR, LOCATION) VALUES ('Whiskers', 5, 'CAT', 'Tabby', 'East Gallery');
INSERT INTO PET (NAME, AGE, PET_TYPE, FUR_COLOUR, LOCATION) VALUES ('Rex', 3, 'DOG', 'Golden', 'North Shelter');
INSERT INTO PET (NAME, AGE, PET_TYPE, FUR_COLOUR, LOCATION) VALUES ('Luna', 1, 'CAT', 'Black', 'West Annex');
INSERT INTO PET (NAME, AGE, PET_TYPE, FUR_COLOUR, LOCATION) VALUES ('Pip', 1, 'BIRD', 'Green', 'North Shelter');
INSERT INTO PET (NAME, AGE, PET_TYPE, FUR_COLOUR, LOCATION) VALUES ('Shadow', 7, 'DOG', 'Black', 'East Gallery');
INSERT INTO PET (NAME, AGE, PET_TYPE, FUR_COLOUR, LOCATION) VALUES ('Bella', 4, 'CAT', 'White', 'West Annex');
INSERT INTO PET (NAME, AGE, PET_TYPE, FUR_COLOUR, LOCATION) VALUES ('Goldie', 2, 'DOG', 'Brown', 'North Shelter');
INSERT INTO PET (NAME, AGE, PET_TYPE, FUR_COLOUR, LOCATION) VALUES ('Bluey', 1, 'BIRD', 'Blue', 'East Gallery');
INSERT INTO PET (NAME, AGE, PET_TYPE, FUR_COLOUR, LOCATION) VALUES ('Oliver', 6, 'CAT', 'Ginger', 'West Annex');



INSERT INTO APP_USER(USERNAME, PASSWORD, PERMISSION_LEVEL) VALUES('mark','a', 'Admin')