CREATE TABLE IF NOT EXISTS PET (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name VARCHAR(255),
    age BIGINT,
    pet_type VARCHAR(50),
    fur_colour VARCHAR(100),
    location VARCHAR(255)
    );